version: '3'
services:
   mongo:
      container_name: mongo
      image: mongo
      # ports:
      #    - '27017:27017'

   api_server:
      build:
         context: ./server
         dockerfile: Dockerfile.dev
      volumes:
         - /app/node_modules
         - ./server:/app
      restart: always

   client:
      build:
         context: ./client
         dockerfile: Dockerfile.dev
      #remove this volume in production
      volumes:
         - /app/node_modules
         - ./client:/app

   nginx:
      restart: always
      build:
         context: ./nginx
         dockerfile: Dockerfile.dev
      ports:
         - '3050:80'
