import Head from 'next/head'
// import Image from 'next/image'

export default function Home() {
   return (
      <div>
         <Head>
            <title>Tolli</title>
            <meta
               name='description'
               content='Generated by create next app'
            />
            <link
               rel='icon'
               href='/favicon.ico'
            />
         </Head>

         <main className=' font-bold  p-16'>
            This page is maanaged by Arun
            prajapati
         </main>
      </div>
   )
}
